[package]
name = "agora-key-share-proofs"
version = "0.1.0"
edition = "2021"

[dependencies]
blsful = "2.5"
hex = "0.4"
rand = "0.8"
serde = "1.0"
serde_bare = "0.5"
thiserror = "1.0"

[dev-dependencies]
maplit = "1"
rand_chacha = "0.3"
serde_json = "1.0"